---

# call this playbook ..

# to extend root disk:
# ansibe-playbook -i hostname.local, -u root -k resize.yaml -e "resizeRoot=true"

# to extend data disk:
# ansibe-playbook -i hostname.local, -u root -k resize.yaml -e "resizeData=true"

# to extend var disk:
# ansibe-playbook -i hostname.local, -u root -k resize.yaml -e "resizeVar=true"

- hosts: all

  tasks:

  # neue virtuelle Platte kommagetrennt unter "pvs:" anfügen
  # add new virtual disk, separated by comma, under "pvs:"
  - name: resize vg by attaching new pv
    lvg:
      vg: rhel
      pvs: /dev/vda2,/dev/vdb,/dev/vdc

  - name: resize FS root
    lvol:
      vg: rhel
      lv: root
      size: +100%FREE
      resizefs: true
    when: resizeRoot == "true"

  - name: resize FS data
    lvol:
      vg: rhel
      lv: data
      size: +100%FREE
      resizefs: true
    when: resizeData == "true"

  - name: resize FS var
    lvol:
      vg: rhel
      lv: var
      size: +100%FREE
      resizefs: true
    when: resizeVar == "true"

